// ignore_for_file: unnecessary_string_escapes
//the same list used in the HTML signup file
const textColor = 0xffb64dfa;
const textColor2 = 0xff4c489d;
var allCities = [
  "Portsaid",
  "Cairo",
  "Alexandria",
  "Giza",
  "Suez",
  "Gharbia",
  "Dakahlia",
  "Asyut",
  "Fayoum",
  "Sharqia",
  "Ismailia",
  "Qalyubia",
  "Aswan",
  "Beheira",
  "Minya",
  "Damietta",
  "Luxor",
  "Qena",
  "Beni Suef",
  "Sohag",
  "Monufia",
  "Hurghada",
  "Banha",
  "Kafr al\-Sheikh",
  "El Arish",
  "Matruh",
];
var allCategories = [
  "Men\-clothes",
  "Women\-clothes",
  "Home Tools",
  "Musical",
  "Kids",
  "Cars",
  "DVDs",
  "Games",
  "Books",
  "Garden",
  "Electerical",
  "Pet Tools",
  "Kitchen",
  "Furniture",
  "Bikes",
  "Sports",
  "Others"
];
